theme: jekyll-theme-cayman
title: Kyungmin Lee
descrption:
show_downloads: false
google_analytics: UA-105629450-1
markdown: kramdown
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
